# Generated by Django 6.0.4 on 2026-05-13 12:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='is_validated',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='validated_by',
        ),
        migrations.AddField(
            model_name='resource',
            name='validated_by',
            field=models.ManyToManyField(blank=True, related_name='validated_resources', to=settings.AUTH_USER_MODEL),
        ),
    ]
