# Generated by Django 6.0.4 on 2026-06-14 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0002_remove_resource_is_validated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(max_length=500, upload_to='shared_resources/'),
        ),
    ]
