# Generated by Django 6.0.4 on 2026-05-13 11:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='validated_by',
            field=models.ManyToManyField(blank=True, related_name='validated_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
