# Generated by Django 6.0.4 on 2026-06-14 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_post_validated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvanalysis',
            name='cv_name',
            field=models.CharField(blank=True, help_text='Name of the uploaded CV file', max_length=255, null=True),
        ),
    ]
